title: <p align="center"> Koteswara Rao Annavarapu </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <div data-proofer-ignore>
  <a href="https://www.linkedin.com/in/kannavarapu/">LinkedIn</a> |
  <a href="https://github.com/kannavar/">GitHub</a>
  </div>
  <br>   
  I am working as a Cloud architect for last 2 years and 
  exploring the data sciene and machine learning area 
  as part of EX.PGP AI&ML courseware
  
  <br>
  </p>

theme: jekyll-theme-minimal
